### ISSUE TITLE
Build from source?

### ISSUE THREAD

**Issue by pelson** [conda-forge/ipywidgets-feedstock#1]
Needs nodejs (packaged): https://github.com/conda-forge/staged-recipes/pull/356#issuecomment-209912363

**Comment by jakirkham** [comment]
We still don't have node? Well, that needs to change.

**Comment by jakirkham** [comment]
LOL. We do have it.

**Comment by SylvainCorlay** [comment]
Well, building ipywidgets from source does not require node. only widgetsnbextension will require it.

**Comment by jakirkham** [comment]
I see. I think we are already doing builds from source here too. So, we should be able to close/move this over to `widgetsnbextension` then. Right?

**Comment by jasongrout** [comment]
I'm confused about what this issue is about, and given that it has not been active for two years, I'm closing it. Feel free to post here to continue the discussion if you'd like to restart the discussion, though.
