### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/ipywidgets-feedstock#20]
When the next ipywidgets conda package will be released?

**Comment by jakirkham** [comment]
I don't understand the question. We already released 6.0.0. What version are you looking for?

**Comment by xmnlab** [comment]
Sorry I should be more specific.

In pypi there is a v7.0.0b1 ... my question is when the v7.0 (final) will be release as a conda package.

Actually I am asking about that because with my current version (6.0) the selected_label parameter of Dropdown widget is not working, and I need to use obj_widget.value to use this functionality:

```python

widgets.Dropdown(
    description='Y:',
    options=all_fields,
    selected_label=field_reference
)
w_field_reference.value = field_reference

```

I have seen some issues, and there it seems to be fixed in master branch.

Sorry, maybe here is not the place to talk about this.

**Comment by jakirkham** [comment]
No worries. It really depends on when upstream cuts 7.0.0 final. Being a package community, that isn't something we can decide here. Would raise an issue on their [repo]( https://github.com/ipython/ipywidgets ) (assuming there isn't one already) asking them their plans for 7.0.0 and see what they say.

**Comment by xmnlab** [comment]
OK! thank you a lot!

**Comment by jakirkham** [comment]
np. Feel free to xref over to that issue from here in case others come asking the same thing. :)
