### ISSUE TITLE
post-link actions are missing but required (by upstream)

### ISSUE THREAD

**Issue by marscher** [conda-forge/ipywidgets-feedstock#31]
similar to widgetsnbextension, which installs and registers the javascript parts of the widgets in the local installation, we need to this for this package as well. in #3 someone stated that is is sufficient to only depend on widgetsnbextension for this purpose, but this does not hold true (any more).
https://github.com/conda-forge/widgetsnbextension-feedstock/blob/master/recipe/post-link.sh

People are getting problems with widgets because they are not installed fully (eg. installed python pkg, javascript extension installed and registered).

cc  https://github.com/conda-forge/nglview-feedstock/issues/5

**Comment by marscher** [comment]
Note that even the maintainers of ipywidgets relied on this fact: https://github.com/jupyter-widgets/ipywidgets#install

**Comment by marscher** [comment]
cc @gph82

**Comment by jasongrout** [comment]
The issue you link above is a problem in the nglview feedstock, not this one. The nglview feedstock should not be a noarch feedstock.

**Comment by hainm** [comment]
@jasongrout  ideally we should not need to do the post-install. I am not convinced to require user to do that. Hopefully notebook folks can have better solution.

**Comment by jakirkham** [comment]
Chiming in here as well to say @jasongrout is correct. `nglview` cannot be `noarch: python` if it needs post-link scripts. Please fix that issue first and see if the problem doesn’t go away.

If you are wanting to use `noarch: python` with post-link scripts, that should be a `conda`/`conda-build` enhancement request not a feedstock issue.

**Comment by jasongrout** [comment]
> @jasongrout ideally we should not need to do the post-install. I am not convinced to require user to do that. Hopefully notebook folks can have better solution.

Agreed (we've all suffered because of this), but that's how the current notebook extension system works. The conversation about a better notebook extension system is over at https://github.com/jupyter/notebook/issues/1706.

**Comment by jasongrout** [comment]
Let's move the discussion about getting nglview working over to https://github.com/conda-forge/nglview-feedstock/issues/5, and the discussion about the notebook extension system (especially if someone wants to work on it!) over to jupyter/notebook#1706.

**Comment by jasongrout** [comment]
Just to be clear for @marscher - no change is needed to this ipywidgets feedstock. The thing that broke the nglview installation was moving it to a noarch package, since noarch packages do not execute post-link scripts. And as @jakirkham pointed out, getting noarch packages to work with post-install scripts is a feature request for conda/conda-build.

**Comment by marscher** [comment]
I have retested with a local build without noarch and still there are no enabled notebook extensions available (py27, will redo with py36). Have you taken a look at the official documentation? The devs there are requiring conda-forge to handle the extensions activation, which is currently not the case.

**Comment by maartenbreddels** [comment]
Hi @marscher 
these are the devs :)
ipywidget does not have the post script to enable the extension, that needs to happen for the widgetsnbextension, which you can find here:
https://github.com/conda-forge/widgetsnbextension-feedstock/tree/master/recipe

**Comment by marscher** [comment]
Hi Maarten,

then I wonder why their extensions are not enabled. But I should report there I'd guess.

Best,
Martin

**Comment by maartenbreddels** [comment]
Try with a new conda env, if you install for instance bqplot or ipyvolume (from conda forge), you should see widgetsnbextensions being installed, and enabled if you do `jupyter nbextension list`.
Note that if you install it from anaconda's main channel, it will not enable (they have a policy of not running post scripts)

**Comment by marscher** [comment]
thanks, will do so.

**Comment by jasongrout** [comment]
@maartenbreddels brings up a good point about channels - our conversation here is about the conda-forge widgetsnbextension, which we maintain. The defaults channel widgetsnbextension package does things a different way. Make sure you're installing the conda-forge channel version for our conversation here.

**Comment by marscher** [comment]
I wrongly named the post/prelink scripts in the nglview feedstock. But even with nglview extension enabled properly the widgets does not show up. It is for sure not an upstream problem. Sorry for causing so much noise!

**Comment by jasongrout** [comment]
> I wrongly named the post/prelink scripts in the nglview feedstock.

Ah, that would do it too :).
