### ISSUE TITLE
enable after installation

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/ipywidgets-feedstock#5]
It would be nice if the recipe could enable the extension after installation, similar to how @SylvainCorlay did with post-* scripts in the pythreejs widget recipe: https://github.com/conda-forge/pythreejs-feedstock/tree/master/recipe. It seems to be a major source of confusion that people have to do `jupyter nbextension enable ...` and get all the arguments right.

**Comment by SylvainCorlay** [comment]
It already does afaik in the widgetsnbextension feedstock.

**Comment by jasongrout** [comment]
ah, perfect!
