### ISSUE TITLE
Can the lab extension installed automatically?

### ISSUE THREAD

**Issue by croth1** [conda-forge/ipywidgets-feedstock#58]
If I understand correctly, the notebook extensions are installed as a dependency automatically, whereas the lab extensions are not.

Would it be technically possible to do something similar with the lab extensions?

**Comment by jasongrout** [comment]
This is done now for JuptyerLab 3 with ipywidgets 7.6, which requires jupyterlab_widgets, which is the JupyterLab 3 widget manager.
