### ISSUE TITLE
Cannot conda install ipywidgets=7.6 with JupyterLab=2

### ISSUE THREAD

**Issue by martinRenou** [conda-forge/ipywidgets-feedstock#65]
It's not possible, due to the `run_constraints` in `jupyterlab_widgets`, to install ipywidgets=7.6 with JupyterLab=2. I understand that it should work with JupyterLab 2 though? Only that jupyterlab_widgets would simply not be used.

**Comment by jasongrout** [comment]
Good point. By itself, that change seemed good, but making jupyterlab_widgets a dependency of ipywidgets makes the change overreaching. I'll remove that line in jupyterlab_widgets feedstock.

**Comment by jasongrout** [comment]
Fixed by https://github.com/conda-forge/jupyterlab_widgets-feedstock/pull/4 - can you check that things work with that build once it is available in conda-forge?

**Comment by jasongrout** [comment]
Installing `ipywidgets=7.6 jupyterlab=2` now works for me.

**Comment by martinRenou** [comment]
Nice! I'll give it a try on my side too.

I am now wondering how we could have an even softer JupyterLab 3 dependency, that doesn't overconstrain the ecosystem. Maybe the jlab version could be specified in the package.json of the federated extension and checked by jlab at runtime?
